Script started on 2016年03月09日 (週三) 22時53分26秒
]0;F74057049@2015cpp: ~/lab1F74057049@2015cpp:~/lab1$ git clone https://github.com/siahuat0727/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Config -l[K[3Pwhoami;pwdgit config -llone https://github.com/siahuat0727/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Kgit clone https://github.com/siahuat0727/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Kg++ o[K-o lab1 lab1.cpp
]0;F74057049@2015cpp: ~/lab1F74057049@2015cpp:~/lab1$ ./lab1
22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 
]0;F74057049@2015cpp: ~/lab1F74057049@2015cpp:~/lab1$ exit

Script done on 2016年03月09日 (週三) 22時54分22秒
